context:
  name: "portal"
  version: "3.8.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/portal-${{ version }}.tar.gz
  sha256: 8abf9620f0772272b7e970ffc8ceccae2f282660f5023eeba9a58dbb2d75d2f8

build:
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - wheel
    - pip
  run:
    - python >=${{ python_min }}
    - cloudpickle
    - msgpack-python
    - numpy
    - psutil

tests:
  - python:
      imports:
        - portal
      python_version: ${{ python_min }}.*

about:
  homepage: http://github.com/danijar/portal
  summary: Fast and reliable distributed systems in Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - noahjutz
